### ISSUE TITLE
raylib new release publish checklist

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#1084]
This is the list with required steps I usually follow to publish a new raylib release, categorized and organized by priority. It's a slow and mostly manual process that really takes long time and effort.

## raylib code update checklist

- [x] Update ALL [raylib/src/external](https://github.com/raysan5/raylib/tree/master/src/external) libraries: [dependencies list](https://github.com/raysan5/raylib/wiki/raylib-dependencies)
- [x] Compile [raylib/src](https://github.com/raysan5/raylib/tree/master/src) for ALL supported platforms -> CI: GitHub Actions, Travis, AppVeyor
- [x] Update and test [raylib/examples](https://github.com/raysan5/raylib/tree/master/examples)
- [x] Update and test [raylib/templates](https://github.com/raysan5/raylib/tree/master/templates)
- [x] Update and test [raylib/games](https://github.com/raysan5/raylib/tree/master/games)

## raylib webpage update checklist

- [x] Update [raylib.com/cheatsheet.html](https://www.raylib.com/cheatsheet/cheatsheet.html) - Add/Review new functionality
- [x] Review [raylib.com/examples.html](https://github.com/raysan5/raylib.com) - Add new examples -> Port examples for web compilation
- [x] Update [raylib.com/games.html](https://github.com/raysan5/raylib.com) - Add new games and recompile for web
- [x] Review [raylib.com/index.html](https://github.com/raysan5/raylib.com) - Add new version features
- [x] Update [raylib ARCHITECTURE image](https://www.raylib.com/images/raylib_architecture_v2.0.png) if required

## raylib GitHub update checklist

- [x] Review [README](https://github.com/raysan5/raylib/blob/master/README.md) - Any addition/modification required?
- [x] Review [HISTORY](https://github.com/raysan5/raylib/blob/master/HISTORY.md) - Add new version evolution comments
- [x] Review [CHANGELOG](https://github.com/raysan5/raylib/blob/master/CHANGELOG) - Check, categorize and format all changes for the release
- [x] Review [CONTRIBUTING](https://github.com/raysan5/raylib/blob/master/CONTRIBUTING.md) - Add new contributors
- [x] Review [ROADMAP](https://github.com/raysan5/raylib/blob/master/ROADMAP) - Review current implementations and add future plans

## raylib package setup checklist

- [x] Update Notepad++ to [latest version](https://notepad-plus-plus.org/downloads/) -> 7.8.4
- [x] Update Notepad++ raylib [functions list xml](https://github.com/raysan5/raylib/blob/master/projects/Notepad%2B%2B/c_raylib.xml)
- [x] Review Notepad++ [compiling scripts](https://github.com/raysan5/raylib/tree/master/projects/Notepad%2B%2B)
- [x] Test Notepad++ compiling scripts
- [x] Update MinGW to latest version -> GCC 8.1
- [x] Update TCC to latest version

## raylib installer package checklist

- [x] Setup package information (version, publisher, …)
- [x] Setup package files (MinGW, Notepad++, raylib)
- [x] Compile package: *raylib_installer_v[x.x].[migw | tcc].exe*
- [x] Test raylib generated package

Please, feel free to comment and give some feedback!

**Comment by raysan5** [comment]
ok, it seems everything is ready... :)
