### ISSUE TITLE
raylib 3.0 roadmap

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#1085]
Actually raylib 3.0 is just an extension to raylib 2.6 but with some big expected changes to the ABI that require lots of redesigns. Check #911 for reference.

Three big changes for this new release:

 - [x] Move all global variables to a global context defined by nested structs. For the moment, context will be defined by module to be self-contained and portable.
 - [x] Complete review and rewrite of logging system. #1065 
 - [x] Support custom memory allocators for raylib and all dependencies. #1074 

Also considering:

 - rnet module addition. #753 -> Requires a full review and rewrite, not possible.

I'll update this issue with further info as required.

**Comment by hbiblia** [comment]
It would be good to separate GLFW3 in order to easily implement another window...

**Comment by raysan5** [comment]
@hbiblia About your points:
1. No plans for that for the moment, you can check `rayfork` project for that approximation.
2. Actually I'd like to remove GLAD and just load the required extensions manually, raylib required OpenGL functionality is very limited, on OpenGL ES 2.0 I'm already doing that...

**Comment by chriscamacho** [comment]
have a look @ https://bitbucket.org/alfonse/glloadgen/wiki/Home
you can generate the core profile you want, then just cull all the stuff you don't need....

**Comment by brankoku** [comment]
If big changes are coming to the ABI, this would be the perfect opportunity to switch from `pass by value` to `pass by reference`. Syntax wouldn't change much, and it's more efficient to pass pointers around instead of filling the stack up with big structures.

**Comment by chriscamacho** [comment]
I agree with @brankoku especially for models, meshes etc...

**Comment by raysan5** [comment]
@brankoku sorry, no plans for that. I already did a big refactor to reduce all structures size, usually under `64 bytes` and unify all structures to be used as pass-by-value (Music was a pointer reference before), I think it's easier for students and overload shouldn't be dramatic.

**Comment by raysan5** [comment]
Implemented global context state in commit https://github.com/raysan5/raylib/commit/40b73a8a91afb26becfcb39560dae73447ce15af.

**Comment by raysan5** [comment]
release publish checklist: #1084

**Comment by chriscamacho** [comment]
Just a thought, is it worth making the "context" structures non-static so more advanced users can make use of them ?

**Comment by pixelblender** [comment]
any plan for iOS support?

**Comment by raysan5** [comment]
@pixelblender no plans for the moment but you can check [rayfork](https://github.com/SasLuca/rayfork), it supports iOS.

**Comment by raysan5** [comment]
raylib 3.0 is complete.
