### ISSUE TITLE
raylib 3.6 roadmap

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#1523]
Here it is my wish list for next raylib version, this time I'll try to keep it smaller and release it earlier, let's see if possible... Feel free to comment here about proposed improvements or, if you have some specific requirement/feature, feel free to comment on [raylib 2021 wishlist Discussion](https://github.com/raysan5/raylib/discussions/1502).

- [x] `core`: Review: `GetFileExtension()` vs `IsFileExtension()` inconsistencies. **_BREAKING CHANGE_**
- [x] `core`: RPI4: Review `Selected DRM connector mode`, it distorts the screen returning a display-supported resolution.
- [x] `core`: Support gamepad mapping/configuration #1506
- [x] `core`: Review high-dpi support... #1086 #1510
- `rlgl`: Consider removing `Texture2D` struct requirement for the low-level API, probably texture id is enough.
- [x] `rlgl`: Redesigned VR simulator to give more control to the user over the fbo and distortion shader
- [x] `rlgl`: Expose the new custom batching system: `rlLoadRenderBatch()`, `rlUpdateRenderBatch()`, `rlDrawRenderBatch()`...
- [x] `rlgl`: Review shader functions naming to follow `rl*()` convention? **_BREAKING CHANGE_**
- [x] `shapes`: Review `DrawRectangleRounded()` performance
- [x] `textures`: Review `DrawTextureTiled()` performance
- `textures`: Allow `RenderTexture.depth` to be `Texture2D` instead of `RenderBuffer` (default)
- `text`: Improve bitmap fonts loading options: `charOrder`, `margin`, `padding`, `backColor`, `keyColor`...
- `text`: Redesign `DrawFPS()` and `DrawGrid()` to support `Color` parameter like other draw functions. **_BREAKING CHANGE_**
- `models`: Break Model loading API into separate functions... #1501 **_BREAKING CHANGE_**
- [x] `models`: Review: `LoadModelAnimations()` requires `UnloadModelAnimations()`
- [x] `models`: Support GLTF animations! #1006
- `raudio`: Provide ring-buffer system, updatable by user -> raw audio management
- [x] `raudio`: Review/redesign (and maybe remove) multi-channel system
- [x] `raudio`: Support `Music` streaming from memory
- [x] `utils`: Expose API callbacks for memory allocation and file access. #1329 #1501 #1521
- [x] `utils`: Review `TraceLog()`, TRACELOGD macro never runs due to logLevel issues
- [x] _`multi`_: Review `return` usage in the middle of functions, I usually try to avoid it and always place return at the EOF.
- [x] _`multi`_: Replace `rlglDraw()` calls by the new batch system: `rlDrawRenderBatchActive()`
- [x] _`multi`_: Review `enums` with prefixes for name consistency  **_BREAKING CHANGE_**
- [x] `examples`: Port some missing examples to web (avoid using `ASYNCIFY`)
- [x] `examples`: Review `core_loading_thread`, it requires raylib compiled with multi-threading support
- [x] `CI/CD`: Support examples building (i.e. when some commit happens in raylib/examples directory)
- [x] `CI/CD`: Support missing configurations building: CMake? 
- `Build`: Automatize installer generation: Inno setup script.

Just note that I'll keep updating this list as required!

**Comment by raysan5** [comment]
-  `rlgl`: Consider removing `Texture2D` struct requirement for the low-level API, probably texture id is enough.

`rlgl` uses `Texture2D` in the following functions:

```c
void rlGenerateMipmaps(Texture2D *texture);                         // Generate mipmap data for selected texture
void *rlReadTexturePixels(Texture2D texture);                       // Read texture pixel data
Texture2D GetTextureDefault(void);                                  // Get default texture
Texture2D GetShapesTexture(void);                                   // Get texture to draw shapes
void SetShapesTexture(Texture2D texture, Rectangle source);
void SetShaderValueTexture(Shader shader, int uniformLoc, Texture2D texture);

TextureCubemap GenTextureCubemap(Shader shader, Texture2D panorama, int size, int format); // Generate cubemap (6 faces) from equirectangular (panorama) texture
Texture2D GenTextureBRDF(Shader shader, int size);                  // Generate a generic BRDF texture
```

Most of them could be changed to just deal with the `id` and `width`/`height` **but** `Texture2D` is used by `Material` struct in `Model`, so, the struct definition can not be removed from `rlgl`, at least for now... It would also require moving `Model` out of `rlgl`.

**Comment by object71** [comment]
@raysan5 
This point - models: Review: LoadModelAnimations() requires UnloadModelAnimations()
There is an existing funciton named **UnloadModelAnimation** (without an 's' in the end)

**Comment by raysan5** [comment]
@object71 yes, I know. The problem here is that `LoadModelAnimations()` allocates de array and also the individual animations but `UnloadModelAnimation()` only frees the individual model animation but not the internally allocated array. There could be situations where raylib default mem allocators are not the same as user code mem allocators, so, it's recommended to use same allocators to alloc/free a piece of memory. Actually, that was the reason to redesign some function with a Load/Unload pair and also the reason to expose `MemAlloc()`/`MemFree()`.

**Comment by raysan5** [comment]
- `text`: Redesign `DrawFPS()` to support `Color` parameter like other draw functions. **_BREAKING CHANGE_**

I decided to just skip this change to avoid lot of breaking... actually, one possible solution would be just add to `raylib.h`:
```c
#define DrawFPS(x,y) DrawFPS(x,y,LIME); 
```

But I considered I doesn't worth it... at least for now... I can live with that function inconsistency...

**Comment by raysan5** [comment]
Multiple enum values have been renamed for consistency and to be more descriptive in commit https://github.com/raysan5/raylib/commit/01e28263be9869b28acae5cf1128472269626edb.

**Comment by raysan5** [comment]
- `text`: Improve bitmap fonts loading options: `charOrder`, `margin`, `padding`, `backColor`, `keyColor`...

After analyzing current implementation:
```c
Font LoadFontFromImage(Image image, Color key, int firstChar);
```
I came to the conclusion that no more parameters are actually required. `margin`/`padding` is checked from pixel `key` color, characters background is expected to be `BLANK` that actually is a nice requirement and requiring a specific `charOrder` starting in the `firstChar` is also as expected, supporting an unordered list of characters would make thinks very complicated; for those cases, user must use an external file defining unicode points and rectangles.

**Comment by raysan5** [comment]
Latest commit https://github.com/raysan5/raylib/commit/ed4ca6a7f386ef6bb86a6016d9e15ecb12ed287f addresses multiple issues.

**Comment by OkiStuff** [comment]
`text`: Redesign `DrawFPS()` to support Color parameter like other draw functions. ***BREAKING CHANGE***
PR to complete this:
https://github.com/raysan5/raylib/pull/1675
The PR also prevents this from being a breaking change

**Comment by raysan5** [comment]
@OkiStuff Thanks for the review, already commented on the PR about the reasons not to merge it. In any case, I'll reviewed the comment.

**Comment by raysan5** [comment]
Very big change introduced in commit https://github.com/raysan5/raylib/commit/cba412cc313e4f95eafb3fba9303400e65c98984

**Comment by raysan5** [comment]
Most of the goals for the next release have been reached. Some features have been omitted and some additional ones implemented. I'm closing this issue, I'll prepare things for a new release. :)
