### ISSUE TITLE
[build] Some build pipeline improvements...

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#377]
Just listing here some build pipeline improvements proposed for implementation, some of them are related to open bugs that I'm closing, this way I've got everything organized in this issue:

 - [x] Support source building with `NO_AUDIO_MODULE` option, it could be useful for applications that do not require audio, like tools, it also avoids linking against OpenAL Soft. Proposed by @gen2brain on https://github.com/raysan5/raylib/issues/372

 - [x] Bundle GLFW3 library on raylib build. GLFW3 dependency (library) on all platforms won't be required because library would be build together with raylib. Proposed by @gen2brain on https://github.com/raysan5/raylib/issues/372

 - [ ] Support raylib minimal version. Minimal raylib version only requires the modules `core`, `rlgl`, `raymath` and `utils`. It can be useful to allow a minimal building for some situations.

 - [ ] Review resources path configuration when building for OSX, it seems there are some problem with resource paths on OSX bundles. This issue has poped up several times and still fails, related issues: #339, #353 and #370. Unfortunately, I don't have a **macOS** platform and can not review it properly... anyone can help on this?

**Comment by akosbalogh** [comment]
Any update on this? I can help you, to make it ok on ubuntu or mac.

**Comment by raysan5** [comment]
Sorry, not yet... today I've been all day (aside of my daily job) working on some RPI issues that popup after updating firmware, some users also ask me for help on [raylib forums](http://forum.raylib.com/index.php?p=/discussions)...

I teacher friend of mine (that is currently teaching raylib) uses OSX and can help on that, hopefully some news soon on that side.

**Comment by raysan5** [comment]
Added GLFW3 sources to raylib and [rglfw](https://github.com/raysan5/raylib/blob/develop/src/rglfw.c) module for integration with raylib. It requires a small modification on GLFW library [internal.h](https://github.com/raysan5/raylib/blob/develop/src/external/glfw/src/internal.h#L28).

**Comment by raysan5** [comment]
Closing this issue.

raylib minimal version support it's a very extreme usage case of the library and requires really a lot of tweaking in main modules to avoid some functions dependencies. Probably most users that require that level of usage will go directly to OpenGL.

About macOS, library and examples building has been improved a lot so I think that's not an issue anymore. If any user still experiment this issue, feel free to reopen this bug.
