### ISSUE TITLE
raylib 2.5 roadmap

### ISSUE THREAD

**Issue by raysan5** [raysan5/raylib#744]
Some days ago I was asked on [raylib Discord](https://discord.gg/mzCY3wN) about the roadmap for the next raylib version. I decided to write this recap issue just for reference.

Next release will be **raylib 2.5** and here it is a list with the new features on this release (in comparison to latest raylib 2.0). Note that some features have already been implemented:

 - [x] [core] Support custom memory allocation macros https://github.com/raysan5/raylib/commit/e67ebabb02c1068d6e7f5107dcff5388ede3faa5
 - [x] [core] Improved UWP support: inputs better integrated with raylib and msgs system implemented
 - [x] [core] Gamepad mechanism: redesign, now common to all platforms and gamepads https://github.com/raysan5/raylib/commit/fc6186a6323029d24ae37b9838fbb509b5aa01f9
 - [x] [core] HiDPI scaling support (issues on macOS https://github.com/raysan5/raylib/issues/837) https://github.com/raysan5/raylib/commit/bb2841a26d2c118b2febfc02c6cab7f7b2791893
 - [x] [rlgl] Complete module redesign to use one single internal buffer
 - [x] [rlgl] Added scissor test functionality: `BeginScisorMode()`/`EndScissorMode()`
 - [x] [rlgl] Support `rlPushMatrix()`/`rlPopMatrix()`, same as OpenGL 1.1
 - [x] [rlgl] Multiple OpenGL ES improvements
 - [x] [rlgl] Improved FBO API to support multiple color/depth formats https://github.com/raysan5/raylib/commit/db56d432e4812f9b21f3548108fb4f1963a81ff5
 - [x] [rlgl] Review VR simulator system, expose parameters and externalize distortion shader https://github.com/raysan5/raylib/commit/5bfa67535040ed1cb717908d9f259db0c302d9e6
 - [x] [text] Added multiple text management functions https://github.com/raysan5/raylib/commit/01338b0a14f053d281970a32595bc531e8c70885
 - [x] [text] Full Unicode text drawing support https://github.com/raysan5/raylib/commit/9ace10ff73a3b7277a2397d79f7827e55a0d83b8
 - [x] [textures] Support cubemap textures generation https://github.com/raysan5/raylib/commit/fce48e85f441215192d188011b48a0f35828e4b3
 - [x] [models] Support skeletal animations https://github.com/raysan5/raylib/commit/92733d6695e0cdab3b42972f2cd6ed48d98ec689
 - [x] [models] Support multiple meshes per model https://github.com/raysan5/raylib/commit/a643dc4ca016ce5791608852ab1357f2d94ebe9b
 - [x] [models] Support glTF model loading (https://github.com/raysan5/raylib/pull/842)
 - [x] [raudio] Multiple improvements to audio module
 - [rlgl] Redesign `GenTexture*()` functions using generic implementations
 - [rnet] Implement basic network module (experimental version)

A part of those points, we have multiple new functions, multiple bugs corrected, multiple new bindings and multiple new examples.

Something missing? Please, drop a comment with your thoughts! :)

**Comment by Demizdor** [comment]
Looks good!

One new feature i would like to see in 2.5 is **clipboard support**...glfw [already has this](https://www.glfw.org/docs/3.0/group__clipboard.html) so Windows, Linux and MacOSX are good to go, just expose the glfw functions...but i don't know how to implement it for other OS'es like Android!

**Comment by raysan5** [comment]
@Demizdor Quickly added in commit https://github.com/raysan5/raylib/commit/e996fe2ff511a60ac67b56996ac04a7e69fe8a69. Not tested yet...

**Comment by overdev** [comment]
Awesome.

Won't raynet module #753 be included in 2.5?

**Comment by raysan5** [comment]
@overdev Not sure if it will get in...

**Comment by hibengler** [comment]
I have successfully integrated raylib with

IOS - That's still needed, right?
Windows under SDL2.0,
Android via NDK
linux using GLFW
It was tricky, as SDL, GLFW, and Raylib all like to be the boss. So to merge these I added a new "PASSIVE" platform that makes raylib passive instead of actively controlling the whole screen.

This allows raylib, and native Open GL ES 2.0 code to work together or independently in the same program.
And the PASSIVE adaptation also supports implementing raylib's VR code to again, both apply to raylib, and native GLES2 code.

Right now, this code is tailored to my open source app SilentRadiance,  but I intend to pull these changes and this option in with your main work.

**Comment by raysan5** [comment]
Hi @hibengler! 

raylib iOS support has been requested several time, that would be a great contribution to the project.
Android via NDK is already supported and GLFW is also used internally by raylib. About SDL2 implementation I understand it's used for Windowing/Context/input management, similar to GLFW?

**Comment by hibengler** [comment]
Yes, SDL 2.0 is very similar to GLFW.  I also use GLFW in my app for linux, but adapted the windows variation to SDL 2.0 to take advantage of a more direct binding to Open GL ES 2.0 on Nvidia hardware, just for the speed increase compared to angle.

I will probably concentrate on iOS then.

Are there still request to improve font support? I have 2 solutions for that : libfreetype to open gl es 2.0 is the most comprehensive, and HibFonts is a fast ascii vector font.  These parts aren't tied to raylib, but they could be.

**Comment by raysan5** [comment]
I'm afraid [rnet](https://github.com/raysan5/raylib/blob/master/src/rnet.c.review) network module won't get into this version, sorry. :(

Also noticed several other improvements that would be great to include, specially the HiDPI support.

**Comment by hibengler** [comment]
Its on the list.  There are two ways to do it.
I could make a SDL #define .

But for Silent Radiance, I made raylib run in a PASSIVE mode, so that my already set up engine could call raylib.

Which would you prefer?

**Comment by raysan5** [comment]
@hibengler I'd like to avoid adding new dependencies to raylib. Is it possible to support iOS with no additional dependencies? Maybe just a .m entry point, similar to Android implementation?

**Comment by raysan5** [comment]
ok, so... it seems all the issues planned for 2.5 (and some more) have been closed... 

Any comments? something left out?

**Comment by a3f** [comment]
- [ ] Update CMake `PROJECT_VERSION`
https://github.com/raysan5/raylib/blob/master/src/CMakeLists.txt#L6

**Comment by jubalh** [comment]
raylib 2.5.0 got released some minutes ago. Congrats!
It's already in openSUSE [repos](https://build.opensuse.org/package/show/devel%3Alibraries%3Ac_c%2B%2B/raylib) by the way!

**Comment by raysan5** [comment]
@jubalh Thank you! :D

I'm working on the raylib 2.5 installers for Windows, hopefully available by the end of day today.

Just for reference, here it is the [complete list of changes](https://github.com/raysan5/raylib/blob/master/CHANGELOG).

**Comment by raysan5** [comment]
[raylib 2.5 release](https://github.com/raysan5/raylib/releases/tag/2.5.0).

**Comment by jubalh** [comment]
> Just for reference, here it is the complete list of changes.

Yep, saw that :)
BTW did you change the interface of any functions? If yes, it might be cool to have an overview for people who use raylib in their projects.

And ABI breakage shouldnt be done on point library release generally. So existing functions shouldnt have their interface changed and no functions removed (ShowLogo()) Just to keep in mind :)

**Comment by raysan5** [comment]
@jubalh Functions flagged as `[REVIEWED]` or `[REMOVED]` could have changed... but I could have missed some function...

About versioning conventions, I usually break API and ABI every new release.
